# Pour plus d'informations sur la navigation: http://wiki.ros.org/nav_core

# See: http://www.ros.org/wiki/navfn
NavfnROS:
  allow_unknown:                      true
  planner_window_x:                   0.0
  planner_window_y:                   0.0
  default_tolerance:                  0.0
  visualize_potential:                false
  planner_costmap_publish_frequency:  1.0

# See: http://wiki.ros.org/global_planner
GlobalPlanner:
  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 253
  allow_unknown: true
  default_tolerance: 0.5
  visualize_potential: true

# See: https://github.com/FontysAtWork/ESA-PROJ/wiki/DWA-Local-Planner
DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 10.0
  acc_lim_theta: 10.0
  
  max_vel_x: 0.4
  min_vel_x: -0.25
  max_rot_vel: 0.4
  min_rot_vel: -0.4

  holonomic_robot: false 
  acc_lim_y: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.2

  # Forward Simulation Parameters
  sim_time: 4.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.10

  vx_samples: 20
  vy_samples: 1
  vth_samples: 40.0

  # Trajectory Scoring Parameters
  path_distance_bias: 1.0
  goal_distance_bias: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  prune_plan: true

# See : http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:
  max_vel_x:              0.25
  min_vel_x:              0.1
  max_vel_theta:          1.0
  min_in_place_vel_theta: -1.0

  acc_lim_x:              0.1
  acc_lim_theta:          0.1

  escape_vel:             -0.1

  # Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y:       0.0
  min_vel_y:       0.0
  acc_lim_y:       0.0

  # Trajectory Scoring Parameters
  meter_scoring: true 
  occdist_scale: 0.01

  dwa: false

  # Goal tolerance
  xy_goal_tolerance:  0.3
  yaw_goal_tolerance: 0.05
