# http://wiki.ros.org/navigation/Tutorials/RobotSetup
# http://www.ros.org/wiki/costmap_2d

# Robot parameters
robot_radius: 0.20
footprint_padding: 0.01

# Sensor management parameter
observation_sources: left_proximity_sensor right_proximity_sensor front_proximity_sensor front_lidar_sensor

left_proximity_sensor: {sensor_frame: front_proximity_sensor, data_type: LaserScan, topic: proximity_sensor/left, expected_update_rate: 0.8, marking: true, clearing: true}
right_proximity_sensor: {sensor_frame: front_proximity_sensor, data_type: LaserScan, topic: proximity_sensor/right, expected_update_rate: 0.8, marking: true, clearing: true}
front_proximity_sensor: {sensor_frame: front_proximity_sensor, data_type: LaserScan, topic: proximity_sensor/front, expected_update_rate: 0.8, marking: true, clearing: true}

front_lidar_sensor: {sensor_frame: front_lidar, data_type: LaserScan, topic: lidar/front, expected_update_rate: 0.8, marking: true, clearing: true}

# Global Filtering Parameters
obstacle_range:    2.5
raytrace_range:    6.0

# ObstacleCostmapPlugin
publish_frequency: 1.0
update_frequency: 2.0
inflation_radius: 1.75

track_unknown_space: false 
footprint_clearing_enabled: true



